# Not to do list api

@baseUrl = http://localhost:8000/api/v1/task

### Get request
GET {{baseUrl}}


### POST the task list
POST {{baseUrl}}

### Update the task list
PUT {{baseUrl}}


### Delete the task list
DELETE {{baseUrl}}