# Not to do list api

@baseUrl = http://localhost:8000/api/v1/tasks

### POST the task list
POST {{baseUrl}}
Content-Type: application/json

{
    "id": 1,
    "task": "Gym",
    "hr": 1,
    "type": "entry"
}

### Get request
GET {{baseUrl}}

### Update the task list
# PUT {{baseUrl}}

PATCH {{baseUrl}}
Content-Type: application/json

{
    "id": 2,
    "type": "bad"
}

### Delete the task list
DELETE {{baseUrl}}/2