# Not to do list api

@baseUrl = http://localhost:8000/api/v1/tasks

### POST the task list
POST {{baseUrl}}
Content-Type: application/json

{
    "task": "coding",
    "hr": 10,
    "type": "entry"
}

### Get request
GET {{baseUrl}}

### Update the task list
# PUT {{baseUrl}}

PATCH {{baseUrl}}
Content-Type: application/json

{
    "_id": "6a409673e649f9949e6b077f",
    "task": "bad"
}

### Delete the task list
DELETE {{baseUrl}}/6a409673e649f9949e6b077f